# Generated by Django 3.1.3 on 2021-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='component',
            field=models.CharField(blank=True, help_text='For what component is this estimate', max_length=100, verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What is the amount of the proposal?', max_digits=10, null=True, verbose_name='Amount'),
        ),
    ]
