# Generated by Django 4.0.2 on 2022-03-26 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esteem', '0003_proposal_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estirequest',
            name='created_by',
            field=models.ForeignKey(help_text='The user who submitted the request', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
