# Generated by Django 4.0.2 on 2022-03-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esteem', '0007_optionmarvindoorexteriorcolor_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estirequestdocument',
            name='estirequest',
            field=models.ForeignKey(help_text='What is the request to which this document is attached?', on_delete=django.db.models.deletion.CASCADE, to='esteem.estirequest', verbose_name='estimate request'),
        ),
        migrations.AlterField(
            model_name='estisheetdoor',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand of these doors?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='estisheetexteriormillwork',
            name='deckingcolor',
            field=models.ForeignKey(blank=True, help_text='What is the decking color?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionexteriormillworkdeckingcolor', verbose_name='decking color'),
        ),
        migrations.AlterField(
            model_name='estisheetexteriormillwork',
            name='deckinggrooves',
            field=models.ForeignKey(blank=True, help_text='What kind of grooving does this decking have?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionexteriormillworkdeckinggrooves', verbose_name='decking grooves'),
        ),
        migrations.AlterField(
            model_name='estisheetexteriormillwork',
            name='optionexteriormillworkdeckingbrand',
            field=models.ForeignKey(blank=True, help_text='What is the decking material?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionexteriormillworkdeckingbrand', verbose_name='decking brand'),
        ),
        migrations.AlterField(
            model_name='estisheetexteriormillwork',
            name='optionexteriormillworkdeckingcollection',
            field=models.ForeignKey(blank=True, help_text='What is the decking collection?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionexteriormillworkdeckingcollection', verbose_name='deckng collection'),
        ),
        migrations.AlterField(
            model_name='estisheetexteriormillwork',
            name='railingstyle',
            field=models.ForeignKey(blank=True, help_text='What is the railing style?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionexteriormillworkrailingstyle', verbose_name='railing style'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='primaryspecies',
            field=models.ForeignKey(blank=True, help_text='What is the primary species for this millwork?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optioninteriormillworkprimaryspecies', verbose_name='primary species'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='stair1riserspecies',
            field=models.ForeignKey(blank=True, help_text='What is the species for this riser?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair1riser', to='esteem.optioninteriormillworkriserspecies', verbose_name='riser species'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='stair1treadspecies',
            field=models.ForeignKey(blank=True, help_text='What is the species for this tread?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair1tread', to='esteem.optioninteriormillworktreadspecies', verbose_name='tread species'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='stair2riserspecies',
            field=models.ForeignKey(blank=True, help_text='What is the species for this riser?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair2riser', to='esteem.optioninteriormillworkriserspecies', verbose_name='riser species'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='stair2treadspecies',
            field=models.ForeignKey(blank=True, help_text='What is the species for this tread?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair2tread', to='esteem.optioninteriormillworktreadspecies', verbose_name='tread species'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='stair3riserspecies',
            field=models.ForeignKey(blank=True, help_text='What is the species for this riser?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair3riser', to='esteem.optioninteriormillworkriserspecies', verbose_name='riser species'),
        ),
        migrations.AlterField(
            model_name='estisheetinteriormillwork',
            name='stair3treadspecies',
            field=models.ForeignKey(blank=True, help_text='What is the species for this tread?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair3tread', to='esteem.optioninteriormillworktreadspecies', verbose_name='tread species'),
        ),
        migrations.AlterField(
            model_name='estisheetmarvindoor',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand of these doors?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='estisheetwindow',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand of these windows?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optiondoorexteriorcolor',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optiondoorhardwarefinish',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optiondoorinteriorfinish',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optiondoorlocksensor',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optiondoorscreen',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optiondoorshade',
            name='optiondoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optiondoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionexteriormillworkdeckingcollection',
            name='optionexteriormillworkdeckingbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionexteriormillworkdeckingbrand', verbose_name='decking brand'),
        ),
        migrations.AlterField(
            model_name='optionexteriormillworkdeckingcolor',
            name='optionexteriormillworkdeckingcollection',
            field=models.ForeignKey(blank=True, help_text='What is the decking collection for which this color is an option?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionexteriormillworkdeckingcollection', verbose_name='decking collection'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorexteriorcolor',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorhardwarefinish',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorhardwarestyle',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorinteriorfinish',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorinteriorspecies',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorlocksensor',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorscreen',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionmarvindoorshade',
            name='optionmarvindoorbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionmarvindoorbrand', verbose_name='door brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowexteriorcolor',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowhardwarefinish',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowinteriorfinish',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowinteriorspecies',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowlocksensor',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowscreen',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
        migrations.AlterField(
            model_name='optionwindowshade',
            name='optionwindowbrand',
            field=models.ForeignKey(blank=True, help_text='What is the brand to which this options applies?', null=True, on_delete=django.db.models.deletion.PROTECT, to='esteem.optionwindowbrand', verbose_name='window brand'),
        ),
    ]
