# Generated by Django 4.0.2 on 2022-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteem', '0008_alter_estirequestdocument_estirequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionexteriormillworkdeckingcolor',
            name='sample',
            field=models.ImageField(blank=True, help_text='What is a sample of the color?', null=True, upload_to='', verbose_name='Sample'),
        ),
        migrations.AddField(
            model_name='optionwindowexteriorcolor',
            name='sample',
            field=models.ImageField(blank=True, help_text='What is a sample of the color?', null=True, upload_to='', verbose_name='Sample'),
        ),
    ]
