# Generated by Django 3.1.3 on 2023-04-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteem', '0010_auto_20230427_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='estirequest',
            name='has_hardware',
            field=models.BooleanField(default=False, help_text='Does this project have Hardware?', verbose_name='hardware'),
        ),
    ]
