# Generated by Django 3.1.3 on 2023-04-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esteem', '0011_estirequest_has_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionHardwareFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='What is the name of this finish?', max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'option hardware finish',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='barndoorhardware',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='barndoorhardwarecomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='deadbolts',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='deadboltscomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='dooraccessories',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='dooraccessoriescomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='electroniclocks',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='electroniclockscomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='entrysets',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='entrysetscomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='keyedknobs',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='keyedknobscomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='knobs',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='knobscomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='sideplatelocks',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='sideplatelockscomments',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='slidingdoorhardware',
        ),
        migrations.RemoveField(
            model_name='estisheethardware',
            name='slidingdoorhardwarecomments',
        ),
        migrations.AddField(
            model_name='estisheethardware',
            name='backset',
            field=models.CharField(blank=True, help_text='What is the backset?', max_length=25, verbose_name='backset'),
        ),
        migrations.AddField(
            model_name='estisheethardware',
            name='doorthickness',
            field=models.CharField(blank=True, help_text='What is the door thickness?', max_length=25, verbose_name='door thickness'),
        ),
        migrations.AddField(
            model_name='estisheethardware',
            name='handlestyle',
            field=models.CharField(blank=True, help_text='What is the handle style?', max_length=25, verbose_name='handle style'),
        ),
        migrations.AddField(
            model_name='estisheethardware',
            name='rosettecode',
            field=models.CharField(blank=True, help_text='What is the rosette code?', max_length=25, verbose_name='rosette code'),
        ),
        migrations.AddField(
            model_name='estisheethardware',
            name='finish',
            field=models.ForeignKey(blank=True, help_text='What is the hardware finish?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esteem.optionhardwarefinish'),
        ),
    ]
